# Use the official Node.js LTS Docker image
image: node:lts

# The name of the job
pages:
  cache:
    paths:
      - node_modules/
  script:
    # Install dependencies
    - npm install
    # Build the project (if necessary, for example for a static site with a framework like Next.js, Gatsby, etc.)
    - npm run build
    # Create the public directory
    - mkdir public
    # Copy everything except the public directory itself
    - find . -maxdepth 1 -mindepth 1 -not -name public -exec cp -r {} public/ \;
  artifacts:
    paths:
      # The folder that contains the files to be exposed at the Page URL
      - public
  rules:
    # This ensures that only pushes to the default branch will trigger
    # a pages deploy
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
